"""Locality-wise monthly rainfall forecasting using seasonal SARIMA.

The production forecast is always generated by a seasonal SARIMA model with
monthly seasonality (period 12). There is deliberately no linear/climatology
fallback: if SARIMA cannot be fitted, the API returns an explicit error rather
than presenting a substitute as a model forecast.
"""

import logging
from pathlib import Path

import numpy as np
import pandas as pd
from statsmodels.tsa.statespace.sarimax import SARIMAX

ROOT = Path(__file__).resolve().parent.parent
DATA_PATH = ROOT / "data" / "raw" / "master_dataset.csv"
LIVE_LOG_PATH = ROOT / "data" / "processed" / "live_rainfall_log.csv"

# 24 complete monthly observations provide two full annual seasonal cycles,
# which is sufficient for the lightweight seasonal SARIMA used here.
MIN_MONTHS = 24

# Seasonal SARIMA candidate configurations. All have monthly seasonality (s=12).
CANDIDATE_MODELS = [
    ((1, 1, 1), (1, 1, 1, 12)),
    ((0, 1, 1), (1, 1, 1, 12)),
    ((1, 1, 0), (1, 1, 1, 12)),
    ((0, 1, 1), (0, 1, 1, 12)),
    ((1, 1, 1), (0, 1, 1, 12)),
]

logger = logging.getLogger(__name__)


def _load_live_log_for_locality(locality: str) -> pd.DataFrame:
    """Return live rainfall observations from PostgreSQL or the CSV fallback."""
    try:
        from backend.database import is_configured
        if is_configured():
            from backend.repositories import rainfall_repository
            return rainfall_repository.read_as_monthly_series(locality)
    except Exception as exc:
        logger.warning("Unable to read live rainfall history for %s: %s", locality, exc)
    return _read_history_file(LIVE_LOG_PATH)


def _read_history_file(path: Path, *, required: bool = False) -> pd.DataFrame:
    if not path.exists():
        if required:
            raise RuntimeError("Required rainfall history dataset is missing")
        return pd.DataFrame(columns=["date", "locality", "rainfall_mm"])

    df = pd.read_csv(path)
    if not {"locality", "rainfall_mm"}.issubset(df.columns):
        raise RuntimeError("Rainfall history dataset has invalid columns")

    if "date" in df.columns:
        dates = pd.to_datetime(df["date"], errors="coerce")
    elif {"year", "month"}.issubset(df.columns):
        dates = pd.to_datetime(
            dict(year=df["year"], month=df["month"], day=1), errors="coerce"
        )
    else:
        raise RuntimeError("Rainfall history dataset needs date or year/month columns")

    df = df.copy()
    df["date"] = dates
    df["rainfall_mm"] = pd.to_numeric(df["rainfall_mm"], errors="coerce")
    return df.dropna(subset=["date", "rainfall_mm"])


def load_locality_monthly(locality: str, data_path: Path = DATA_PATH) -> pd.Series:
    """Load a continuous monthly rainfall series for one locality."""
    base = _read_history_file(data_path, required=True)
    live = _load_live_log_for_locality(locality)

    frames = [base]
    if not live.empty:
        frames.append(live)
    df = pd.concat(frames, ignore_index=True)

    mask = df["locality"].astype(str).str.lower().eq(locality.lower())
    subset = df.loc[mask].copy()
    if subset.empty:
        raise ValueError(f"Unknown locality or no rainfall history: {locality}")

    current_month_start = pd.Timestamp.today().replace(
        day=1, hour=0, minute=0, second=0, microsecond=0
    )
    subset = subset[subset["date"] < current_month_start]

    subset = subset.sort_values("date", kind="mergesort").drop_duplicates(
        subset=["date"], keep="last"
    )

    monthly = (
        subset.set_index("date")["rainfall_mm"]
        .resample("MS")
        .sum(min_count=1)
    )

    if monthly.empty:
        raise ValueError(f"No complete monthly rainfall history for {locality}")

    # Make the monthly index explicit and regular for seasonal SARIMA.
    full_index = pd.date_range(monthly.index.min(), monthly.index.max(), freq="MS")
    monthly = monthly.reindex(full_index)

    # Historical records are sparse for some localities. Do not interpret those
    # old gaps as zero rainfall and do not fill them artificially. Instead,
    # train on the latest contiguous monthly block available before forecasting.
    # This preserves a genuine SARIMA input series while using the recent
    # backfilled 2024-present rainfall data.
    available = monthly.notna()
    if not available.any():
        raise ValueError(f"No usable monthly rainfall history for {locality}")

    end_pos = len(monthly) - 1
    while end_pos >= 0 and pd.isna(monthly.iloc[end_pos]):
        end_pos -= 1

    start_pos = end_pos
    while start_pos > 0 and pd.notna(monthly.iloc[start_pos - 1]):
        start_pos -= 1

    recent = monthly.iloc[start_pos:end_pos + 1].copy()

    if len(recent) < MIN_MONTHS:
        raise ValueError(
            f"Rainfall history for {locality} has only {len(recent)} consecutive "
            f"complete months; SARIMA requires at least {MIN_MONTHS}."
        )

    return recent


def _fit_sarima(series: pd.Series, order: tuple, seasonal_order: tuple):
    """Fit one seasonal SARIMA candidate and return the fitted model."""
    train = series.astype(float)
    if train.isna().mean() > 0.10:
        raise ValueError("Too many missing monthly observations for SARIMA")

    return SARIMAX(
        train,
        order=order,
        seasonal_order=seasonal_order,
        enforce_stationarity=False,
        enforce_invertibility=False,
        trend=None,
    ).fit(disp=False, maxiter=300)


def _select_model(series: pd.Series):
    """Select the lowest-AIC successful seasonal SARIMA candidate."""
    best = None
    failures = []

    for order, seasonal_order in CANDIDATE_MODELS:
        try:
            fit = _fit_sarima(series, order, seasonal_order)
            aic = float(fit.aic)

            if not np.isfinite(aic):
                raise ValueError("non-finite AIC")

            candidate = (aic, order, seasonal_order, fit)
            if best is None or aic < best[0]:
                best = candidate
        except Exception as exc:
            failures.append(f"{order}x{seasonal_order}: {exc}")

    if best is None:
        detail = "; ".join(failures[:5])
        raise RuntimeError(
            f"No seasonal SARIMA candidate could be fitted for the locality. "
            f"Attempts: {detail}"
        )

    return best


def _forecast_dates(start_date: pd.Timestamp, horizon_months: int) -> pd.DatetimeIndex:
    return pd.date_range(start=start_date, periods=horizon_months, freq="MS")


def forecast_locality(
    locality: str,
    horizon_months: int = 12,
    data_path: Path = DATA_PATH,
) -> dict:
    if horizon_months not in (6, 12, 24, 36):
        raise ValueError("horizon_months must be 6, 12, 24, or 36")

    monthly = load_locality_monthly(locality, data_path)
    observed = monthly.dropna()

    if len(observed) < MIN_MONTHS:
        raise ValueError(
            f"SARIMA requires at least {MIN_MONTHS} complete monthly observations; "
            f"{locality} has {len(observed)}."
        )

    training_end_ts = monthly.index.max()
    forecast_start_ts = training_end_ts + pd.DateOffset(months=1)

    aic, order, seasonal_order, fit = _select_model(monthly)

    future = fit.get_forecast(steps=horizon_months)
    ci = future.conf_int(alpha=0.05)

    mean = np.maximum(
        np.asarray(future.predicted_mean, dtype=float),
        0.0,
    )
    lower = np.maximum(
        np.asarray(ci.iloc[:, 0], dtype=float),
        0.0,
    )
    upper = np.maximum(
        np.asarray(ci.iloc[:, 1], dtype=float),
        0.0,
    )

    dates = _forecast_dates(forecast_start_ts, horizon_months)

    rows = [
        {
            "month": dates[i].strftime("%Y-%m"),
            "forecast_mm": round(float(mean[i]), 2),
            "lower_95_mm": round(float(lower[i]), 2),
            "upper_95_mm": round(float(upper[i]), 2),
        }
        for i in range(horizon_months)
    ]

    return {
        "locality": locality,
        "status": "ok",
        "message": "Locality-specific seasonal SARIMA forecast",
        "observed_months": int(len(observed)),
        "first_observation": str(observed.index.min().date()),
        "last_observation": str(observed.index.max().date()),
        "training_start": observed.index.min().strftime("%Y-%m"),
        "training_end": training_end_ts.strftime("%Y-%m"),
        "forecast_start": forecast_start_ts.strftime("%Y-%m"),
        "horizon_months": horizon_months,
        "model": {
            "name": "SARIMA",
            "order": list(order),
            "seasonal_order": list(seasonal_order),
            "seasonal_period": 12,
            "aic": round(aic, 2),
        },
        "forecast": rows,
        "forecast_total_mm": round(sum(x["forecast_mm"] for x in rows), 2),
    }
